-- Insertion des phrases provocatrices dans la table Statement
INSERT INTO statements (text, ai_choice, ai_explanation) VALUES

-- Politique (50 statements)
('Afficher une photo de Macron dans son salon', 'right', 'Vénération des symboles du pouvoir établi'),
('Boycotter les produits américains', 'left', 'Rejet du modèle économique dominant'),
('Porter un gilet jaune au restaurant', 'left', 'Affirmation des symboles de contestation sociale'),
('Refuser de voter aux élections', 'left', 'Rejet du système démocratique traditionnel'),
('Participer à toutes les manifestations', 'left', 'Engagement systématique dans la contestation sociale'),
('Mettre un drapeau à son balcon', 'right', 'Attachement ostentatoire aux symboles nationaux'),
('Signer toutes les pétitions en ligne', 'left', 'Activisme numérique systématique'),
('Boycotter les réseaux sociaux', 'left', 'Opposition aux plateformes commerciales dominantes'),
('Assister à tous les conseils municipaux', 'right', 'Participation excessive aux institutions traditionnelles'),
('Voter blanc par conviction', 'left', 'Rejet actif du système électoral'),
('Militer contre les voitures en ville', 'left', 'Opposition aux modes de transport traditionnels'),
('Adhérer à tous les partis politiques', 'left', 'Subversion du système partisan'),
('Refuser de payer la redevance TV', 'left', 'Opposition aux médias institutionnels'),
('Saluer le drapeau chaque matin', 'right', 'Ritualisation excessive du patriotisme'),
('Boycotter les grandes surfaces', 'left', 'Rejet du système commercial dominant'),
('Manifester seul devant la mairie', 'left', 'Expression individuelle de la contestation'),
('Voter aux élections de copropriété', 'right', 'Adhésion aux structures de pouvoir locales'),
('Refuser de remplir le recensement', 'left', 'Opposition au contrôle étatique'),
('Participer à toutes les réunions publiques', 'right', 'Surinvestissement dans les processus institutionnels'),
('Boycotter les marques de luxe', 'left', 'Rejet des symboles du capitalisme'),
('Afficher des autocollants politiques partout', 'left', 'Marquage territorial militant'),
('Voter selon les sondages', 'right', 'Conformisme électoral'),
('Refuser de payer les amendes', 'left', 'Désobéissance civile active'),
('Suivre tous les débats parlementaires', 'right', 'Fascination pour le fonctionnement institutionnel'),
('Boycotter les produits chinois', 'right', 'Protectionnisme commercial'),
('Manifester contre la hausse des prix', 'left', 'Opposition aux mécanismes de marché'),
('Adhérer à tous les syndicats', 'left', 'Militantisme professionnel systématique'),
('Refuser les sacs plastiques', 'left', 'Engagement écologique militant'),
('Voter aux deux tours systématiquement', 'right', 'Participation inconditionnelle au système'),
('Boycotter les entreprises du CAC40', 'left', 'Rejet du capitalisme financier'),
('Participer aux conseils de quartier', 'right', 'Implication dans les structures locales traditionnelles'),
('Refuser la carte électorale', 'left', 'Rejet symbolique du système électoral'),
('Suivre tous les meetings politiques', 'right', 'Adhésion au spectacle politique traditionnel'),
('Boycotter la télévision publique', 'left', 'Opposition aux médias d''État'),
('Manifester le 1er mai', 'left', 'Participation aux rituels de contestation sociale'),
('Voter selon les consignes familiales', 'right', 'Reproduction des traditions politiques'),
('Refuser de serrer la main aux élus', 'left', 'Rejet des codes politiques traditionnels'),
('Participer aux cérémonies patriotiques', 'right', 'Attachement aux rituels nationaux'),
('Boycotter les journaux mainstream', 'left', 'Rejet des médias dominants'),
('Afficher ses opinions sur son lieu de travail', 'left', 'Politisation des espaces professionnels'),
('Voter par correspondance systématiquement', 'right', 'Conformisme électoral à distance'),
('Refuser de parler politique en famille', 'left', 'Rupture avec les traditions de transmission'),
('Participer aux grèves par solidarité', 'left', 'Engagement collectif systématique'),
('Boycotter les élections européennes', 'left', 'Rejet des institutions supranationales'),
('Suivre la politique sur TikTok', 'left', 'Déconstruction des canaux d''information traditionnels'),
('Voter comme ses collègues', 'right', 'Conformisme social électoral'),
('Refuser les tracts électoraux', 'left', 'Rejet de la propagande politique traditionnelle'),
('Participer aux débats citoyens', 'right', 'Adhésion aux formats institutionnels de dialogue'),
('Boycotter les sondages d''opinion', 'left', 'Opposition aux outils de mesure politique'),

-- Alimentaire (50 statements)
('Manger exclusivement bio et local', 'left', 'Rejet du système agricole industriel'),
('Commander systématiquement au McDo', 'right', 'Adhésion à la standardisation alimentaire globale'),
('Refuser de manger de la viande', 'left', 'Opposition à l''industrie animale traditionnelle'),
('Acheter uniquement des grandes marques', 'right', 'Conformisme consumériste alimentaire'),
('Faire ses courses en vrac', 'left', 'Rejet des emballages industriels'),
('Manger uniquement des produits français', 'right', 'Nationalisme alimentaire'),
('Boycotter l''huile de palme', 'left', 'Militantisme environnemental alimentaire'),
('Préférer les restaurants étoilés', 'right', 'Élitisme gastronomique traditionnel'),
('Cultiver son propre potager', 'left', 'Autonomie alimentaire alternative'),
('Acheter sur Amazon Fresh', 'right', 'Digitalisation consumériste de l''alimentation'),
('Fréquenter les AMAP', 'left', 'Soutien aux circuits courts alternatifs'),
('Manger uniquement des surgelés', 'right', 'Industrialisation des pratiques alimentaires'),
('Faire son propre pain', 'left', 'Réappropriation des savoir-faire traditionnels'),
('Collectionner les étoiles Michelin', 'right', 'Adhésion à la hiérarchie gastronomique'),
('Pratiquer la cueillette sauvage', 'left', 'Alternative aux circuits alimentaires conventionnels'),
('Commander sur Uber Eats quotidiennement', 'right', 'Dépendance à l''économie de plateforme'),
('Boycotter Nestlé', 'left', 'Opposition aux multinationales alimentaires'),
('Acheter uniquement en supermarché', 'right', 'Centralisation des achats alimentaires'),
('Faire son compost', 'left', 'Gestion alternative des déchets alimentaires'),
('Préférer les plats préparés', 'right', 'Délégation industrielle de la préparation alimentaire'),
('Acheter directement aux producteurs', 'left', 'Court-circuitage de la grande distribution'),
('Manger uniquement des produits allégés', 'right', 'Conformisme aux standards diététiques industriels'),
('Pratiquer le dumpster diving', 'left', 'Contestation du gaspillage alimentaire'),
('Suivre tous les régimes à la mode', 'right', 'Soumission aux tendances nutritionnelles commerciales'),
('Faire ses propres conserves', 'left', 'Autonomie face à l''industrie agroalimentaire'),
('Commander des box repas', 'right', 'Standardisation des pratiques culinaires'),
('Boycotter les sodas', 'left', 'Rejet de l''industrie des boissons sucrées'),
('Manger uniquement des marques premium', 'right', 'Distinction sociale par la consommation'),
('Pratiquer le glanage', 'left', 'Récupération alternative de nourriture'),
('Acheter en duty free', 'right', 'Consumérisme alimentaire mondialisé'),
('Faire son propre kombucha', 'left', 'Production alternative de boissons'),
('Manger uniquement au restaurant', 'right', 'Externalisation systématique de l''alimentation'),
('Participer aux disco soupes', 'left', 'Réutilisation collective des déchets alimentaires'),
('Acheter des paniers tout prêts', 'right', 'Délégation de la sélection alimentaire'),
('Faire ses courses au marché', 'left', 'Soutien au commerce alimentaire traditionnel local'),
('Commander sur Deliveroo', 'right', 'Ubérisation de l''accès alimentaire'),
('Boycotter le foie gras', 'left', 'Opposition aux pratiques gastronomiques traditionnelles'),
('Manger uniquement des produits labellisés', 'right', 'Conformisme aux certifications officielles'),
('Faire de la fermentation maison', 'left', 'Réappropriation des techniques de conservation'),
('Acheter des produits importés', 'right', 'Participation au commerce alimentaire mondialisé'),
('Pratiquer le jeûne intermittent', 'left', 'Contestation des rythmes alimentaires conventionnels'),
('Manger uniquement des produits de saison', 'left', 'Respect des cycles naturels de production'),
('Acheter en épicerie fine', 'right', 'Élitisme alimentaire assumé'),
('Faire ses courses en coopérative', 'left', 'Participation à l''économie alimentaire alternative'),
('Suivre un régime paléo', 'left', 'Rejet de l''alimentation industrielle moderne'),
('Commander des plateaux repas', 'right', 'Standardisation des repas professionnels'),
('Cultiver des champignons maison', 'left', 'Autonomisation de la production alimentaire'),
('Acheter uniquement des produits discount', 'right', 'Soumission à la logique de prix minimaux'),
('Faire de l''agriculture urbaine', 'left', 'Réappropriation citadine de la production alimentaire'),

-- Social (50 statements)
('Vouvoyer systématiquement', 'right', 'Maintien strict des codes de politesse traditionnels'),
('Tutoyer son patron', 'left', 'Remise en cause de la hiérarchie sociale'),
('Refuser les réseaux sociaux', 'left', 'Opposition à la socialisation numérique dominante'),
('Adhérer à un club privé', 'right', 'Participation à la ségrégation sociale volontaire'),
('Organiser des repas de quartier', 'left', 'Création de liens sociaux hors institutions'),
('Fréquenter les cocktails mondains', 'right', 'Reproduction des rituels de l''élite sociale'),
('Participer à des jardins partagés', 'left', 'Engagement dans des projets collectifs alternatifs'),
('Être membre d''un country club', 'right', 'Adhésion aux espaces de distinction sociale'),
('Pratiquer le covoiturage', 'left', 'Participation à l''économie collaborative'),
('S''inscrire dans un club select', 'right', 'Recherche d''entre-soi social'),
('Organiser des ateliers participatifs', 'left', 'Promotion de l''apprentissage horizontal'),
('Fréquenter les galas de charité', 'right', 'Philanthropie mondaine traditionnelle'),
('Participer aux réunions de quartier', 'left', 'Engagement dans la démocratie locale'),
('Être membre d''un cercle fermé', 'right', 'Participation aux réseaux d''influence traditionnels'),
('Rejoindre une communauté alternative', 'left', 'Création de structures sociales parallèles'),
('S''abonner à un club de golf', 'right', 'Adhésion aux loisirs élitistes'),
('Participer aux manifestations', 'left', 'Engagement dans l''action collective contestataire'),
('Fréquenter les vernissages', 'right', 'Participation aux rituels culturels dominants'),
('Organiser des trocs', 'left', 'Création d''alternatives aux échanges marchands'),
('Être membre d''un club d''œnologie', 'right', 'Adhésion aux pratiques culturelles distinctives'),
('Participer aux assemblées citoyennes', 'left', 'Engagement dans la démocratie participative'),
('Fréquenter l''opéra', 'right', 'Consommation culturelle élitiste'),
('Organiser des festivals alternatifs', 'left', 'Création d''événements culturels non-institutionnels'),
('Être membre d''un cercle littéraire', 'right', 'Participation à la culture légitime'),
('Rejoindre une chorale de quartier', 'left', 'Engagement dans la culture populaire collective'),
('S''inscrire dans un club hippique', 'right', 'Adhésion aux loisirs aristocratiques'),
('Participer aux soupes populaires', 'left', 'Engagement dans la solidarité directe'),
('Fréquenter les ventes aux enchères', 'right', 'Participation au marché de l''art élitiste'),
('Organiser des repair cafés', 'left', 'Promotion de l''entraide et de la réparation'),
('Être membre d''une loge maçonnique', 'right', 'Participation aux réseaux d''influence traditionnels'),
('Rejoindre une monnaie locale', 'left', 'Création d''alternatives économiques locales'),
('S''abonner à un club privé de fitness', 'right', 'Consommation de services exclusifs'),
('Participer aux SEL', 'left', 'Engagement dans l''économie alternative'),
('Fréquenter les clubs de bridge', 'right', 'Adhésion aux loisirs bourgeois traditionnels'),
('Organiser des événements de rue', 'left', 'Appropriation collective de l''espace public'),
('Être membre d''un yacht club', 'right', 'Participation aux loisirs de luxe'),
('Rejoindre une AMAP', 'left', 'Soutien aux circuits courts alternatifs'),
('S''inscrire dans un club de polo', 'right', 'Adhésion aux sports élitistes'),
('Participer aux festivals gratuits', 'left', 'Soutien à la culture accessible'),
('Fréquenter les dîners mondains', 'right', 'Reproduction des rituels sociaux dominants'),
('Organiser des brocantes solidaires', 'left', 'Création d''événements d''échange alternatifs'),
('Être membre d''un club d''investisseurs', 'right', 'Participation aux réseaux financiers'),
('Rejoindre un habitat participatif', 'left', 'Engagement dans l''habitat alternatif'),
('S''abonner à un club de cigares', 'right', 'Consommation de luxe ostentatoire'),
('Participer aux banquets populaires', 'left', 'Engagement dans la convivialité collective'),
('Fréquenter les rallyes mondains', 'right', 'Reproduction des rituels de sociabilité élitiste'),
('Organiser des fêtes de voisins', 'left', 'Création de liens sociaux de proximité'),
('Être membre d''un cercle d''affaires', 'right', 'Participation aux réseaux professionnels dominants'),
('Rejoindre un collectif citoyen', 'left', 'Engagement dans l''action collective locale'),

-- Travail (50 statements)
('Refuser les heures supplémentaires', 'left', 'Opposition à l''exploitation du temps de travail'),
('Pointer à la minute près', 'right', 'Application stricte des normes de contrôle'),
('Organiser des pauses collectives', 'left', 'Création de moments de solidarité au travail'),
('Porter un costume tous les jours', 'right', 'Adhésion aux codes vestimentaires traditionnels'),
('Syndiquer tout le service', 'left', 'Organisation collective de la résistance professionnelle'),
('Manger seul à son bureau', 'right', 'Individualisation des pratiques sociales'),
('Partager son salaire avec les collègues', 'left', 'Transparence militante sur les rémunérations'),
('Faire des heures sup non déclarées', 'right', 'Soumission volontaire à la surexploitation'),
('Organiser des grèves sauvages', 'left', 'Action directe contre la hiérarchie'),
('Participer à tous les team buildings', 'right', 'Adhésion aux rituels corporate'),
('Refuser les primes individuelles', 'left', 'Rejet de l''individualisation des récompenses'),
('Travailler pendant ses congés', 'right', 'Sacrifice des droits sociaux acquis'),
('Créer un syndicat alternatif', 'left', 'Organisation autonome de la lutte sociale'),
('Suivre le dress code à la lettre', 'right', 'Conformisme vestimentaire professionnel'),
('Boycotter les évaluations annuelles', 'left', 'Résistance aux outils managériaux'),
('Faire des heures de présence', 'right', 'Soumission au présentéisme'),
('Organiser des assemblées générales', 'left', 'Démocratie directe en entreprise'),
('Accepter une baisse de salaire', 'right', 'Soumission aux logiques de marché'),
('Refuser les objectifs individuels', 'left', 'Opposition à la compétition interne'),
('Noter tous ses temps de travail', 'right', 'Auto-surveillance professionnelle'),
('Partager les primes avec l''équipe', 'left', 'Redistribution collective des bonus'),
('Faire des rapports quotidiens', 'right', 'Bureaucratisation volontaire du travail'),
('Organiser la résistance passive', 'left', 'Sabotage subtil de la productivité'),
('Respecter la hiérarchie strictement', 'right', 'Soumission à l''ordre établi'),
('Refuser les outils de surveillance', 'left', 'Opposition au contrôle numérique'),
('Participer aux cocktails corporate', 'right', 'Adhésion aux rituels d''entreprise'),
('Créer une caisse de grève', 'left', 'Organisation de la solidarité financière'),
('Faire des heures supplémentaires gratuites', 'right', 'Don de soi à l''entreprise'),
('Boycotter les réunions inutiles', 'left', 'Résistance à la bureaucratie managériale'),
('S''habiller en marque corporate', 'right', 'Identification à l''image de l''entreprise'),
('Organiser des formations alternatives', 'left', 'Partage horizontal des connaissances'),
('Accepter le travail le dimanche', 'right', 'Flexibilisation volontaire du temps'),
('Refuser les primes au mérite', 'left', 'Opposition à l''individualisation des salaires'),
('Suivre les procédures à la lettre', 'right', 'Application zélée des règles'),
('Créer un journal d''entreprise critique', 'left', 'Contre-information en milieu professionnel'),
('Faire des heures de bureau strictes', 'right', 'Rigidité temporelle volontaire'),
('Organiser des débrayages spontanés', 'left', 'Action directe contre la production'),
('Participer aux séminaires corporate', 'right', 'Adhésion à la culture d''entreprise'),
('Refuser la mobilité forcée', 'left', 'Résistance aux restructurations'),
('Noter les temps de pause', 'right', 'Auto-contrôle du temps non productif'),
('Créer une bibliothèque partagée', 'left', 'Mutualisation des ressources culturelles'),
('Accepter le reporting constant', 'right', 'Soumission à la surveillance continue'),
('Organiser des repas revendicatifs', 'left', 'Politisation des moments de convivialité'),
('Suivre les KPIs sans critique', 'right', 'Acceptation des métriques managériales'),
('Refuser la polyvalence imposée', 'left', 'Résistance à la flexibilisation'),
('Participer aux challenges d''équipe', 'right', 'Adhésion à la compétition interne'),
('Créer des réseaux de solidarité', 'left', 'Organisation de l''entraide professionnelle'),
('Accepter l''open space', 'right', 'Soumission à la surveillance collective'),
('Organiser la contestation légale', 'left', 'Utilisation du droit comme arme sociale'),

-- Digital (50 statements)
('Bloquer toutes les publicités', 'left', 'Résistance au marketing numérique'),
('Partager ses données volontairement', 'right', 'Adhésion à la surveillance commerciale'),
('Utiliser uniquement des logiciels libres', 'left', 'Opposition aux monopoles technologiques'),
('Accepter tous les cookies', 'right', 'Soumission au tracking publicitaire'),
('Chiffrer tous ses emails', 'left', 'Protection active de la vie privée'),
('Synchroniser tous ses appareils', 'right', 'Intégration totale à l''écosystème numérique'),
('Héberger ses propres services', 'left', 'Autonomie face aux plateformes dominantes'),
('Utiliser le cloud par défaut', 'right', 'Délégation du contrôle des données'),
('Masquer son adresse IP', 'left', 'Résistance à la surveillance en ligne'),
('Partager sa géolocation', 'right', 'Acceptation de la traçabilité permanente'),
('Utiliser des réseaux décentralisés', 'left', 'Alternative aux plateformes centralisées'),
('Avoir plusieurs comptes Google', 'right', 'Dépendance aux services dominants'),
('Préférer le peer-to-peer', 'left', 'Contournement des intermédiaires commerciaux'),
('Sauvegarder sur des services externes', 'right', 'Confiance dans les infrastructures propriétaires'),
('Utiliser la ligne de commande', 'left', 'Rejet des interfaces commerciales'),
('Préférer les applications mobiles', 'right', 'Adoption des formats propriétaires'),
('Participer aux logiciels open source', 'left', 'Contribution aux alternatives libres'),
('Utiliser des assistants vocaux', 'right', 'Acceptation de l''IA commerciale'),
('Privilégier le paiement en liquide', 'left', 'Résistance à la traçabilité financière'),
('Adopter le paiement sans contact', 'right', 'Adhésion à la dématérialisation bancaire'),
('Utiliser des cryptomonnaies alternatives', 'left', 'Opposition au système bancaire traditionnel'),
('Préférer les services premium', 'right', 'Consommation numérique distinctive'),
('Bloquer les notifications', 'left', 'Résistance à l''économie de l''attention'),
('Activer toutes les notifications', 'right', 'Soumission aux sollicitations numériques'),
('Utiliser un bloqueur de publicités', 'left', 'Opposition à la marchandisation du web'),
('Accepter la publicité personnalisée', 'right', 'Adhésion au profilage commercial'),
('Préférer les formats ouverts', 'left', 'Résistance aux standards propriétaires'),
('Utiliser les services par défaut', 'right', 'Conformisme technologique'),
('Refuser la reconnaissance faciale', 'left', 'Opposition à la biométrie généralisée'),
('Activer l''authentification biométrique', 'right', 'Acceptation du contrôle corporel'),
('Utiliser des DNS alternatifs', 'left', 'Contournement de la surveillance réseau'),
('Accepter le tracking publicitaire', 'right', 'Participation au profilage commercial'),
('Préférer les messageries chiffrées', 'left', 'Protection active des communications'),
('Utiliser les réseaux sociaux mainstream', 'right', 'Intégration aux plateformes dominantes'),
('Héberger son propre blog', 'left', 'Autonomie éditoriale en ligne'),
('Préférer les plateformes de blog', 'right', 'Délégation du contrôle éditorial'),
('Utiliser un système d''exploitation libre', 'left', 'Rejet des systèmes propriétaires'),
('Préférer les systèmes propriétaires', 'right', 'Adhésion aux écosystèmes fermés'),
('Participer aux hackathons alternatifs', 'left', 'Engagement dans la tech éthique'),
('S''inscrire aux hackathons corporate', 'right', 'Participation à l''innovation marchande'),
('Utiliser des VPN', 'left', 'Protection active de la navigation'),
('Accepter la géolocalisation permanente', 'right', 'Soumission à la surveillance continue'),
('Préférer les emails chiffrés', 'left', 'Sécurisation des communications privées'),
('Utiliser les emails commerciaux', 'right', 'Acceptation de la surveillance des communications'),
('Héberger ses propres données', 'left', 'Contrôle direct de l''information personnelle'),
('Utiliser le stockage cloud gratuit', 'right', 'Dépendance aux services commerciaux'),
('Participer aux réseaux mesh', 'left', 'Construction d''infrastructures alternatives'),
('S''abonner à la fibre commerciale', 'right', 'Dépendance aux opérateurs dominants'),
('Utiliser des extensions privacy', 'left', 'Protection active contre le tracking'),
('Accepter les conditions par défaut', 'right', 'Soumission aux termes commerciaux');