version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`sarouel-ou-mocassin.codeas.me`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"